package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SevGraficaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSevGraficaAllPropertiesEquals(SevGrafica expected, SevGrafica actual) {
        assertSevGraficaAutoGeneratedPropertiesEquals(expected, actual);
        assertSevGraficaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSevGraficaAllUpdatablePropertiesEquals(SevGrafica expected, SevGrafica actual) {
        assertSevGraficaUpdatableFieldsEquals(expected, actual);
        assertSevGraficaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSevGraficaAutoGeneratedPropertiesEquals(SevGrafica expected, SevGrafica actual) {
        assertThat(expected)
            .as("Verify SevGrafica auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSevGraficaUpdatableFieldsEquals(SevGrafica expected, SevGrafica actual) {
        assertThat(expected)
            .as("Verify SevGrafica relevant properties")
            .satisfies(e -> assertThat(e.getIdGrafica()).as("check idGrafica").isEqualTo(actual.getIdGrafica()))
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getFkIdResponsable()).as("check fkIdResponsable").isEqualTo(actual.getFkIdResponsable()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSevGraficaUpdatableRelationshipsEquals(SevGrafica expected, SevGrafica actual) {
        assertThat(expected)
            .as("Verify SevGrafica relationships")
            .satisfies(e -> assertThat(e.getProceso()).as("check proceso").isEqualTo(actual.getProceso()));
    }
}
