package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SevProcesoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSevProcesoAllPropertiesEquals(SevProceso expected, SevProceso actual) {
        assertSevProcesoAutoGeneratedPropertiesEquals(expected, actual);
        assertSevProcesoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSevProcesoAllUpdatablePropertiesEquals(SevProceso expected, SevProceso actual) {
        assertSevProcesoUpdatableFieldsEquals(expected, actual);
        assertSevProcesoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSevProcesoAutoGeneratedPropertiesEquals(SevProceso expected, SevProceso actual) {
        assertThat(expected)
            .as("Verify SevProceso auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSevProcesoUpdatableFieldsEquals(SevProceso expected, SevProceso actual) {
        assertThat(expected)
            .as("Verify SevProceso relevant properties")
            .satisfies(e -> assertThat(e.getIdProceso()).as("check idProceso").isEqualTo(actual.getIdProceso()))
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getFkIdResponsable()).as("check fkIdResponsable").isEqualTo(actual.getFkIdResponsable()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSevProcesoUpdatableRelationshipsEquals(SevProceso expected, SevProceso actual) {
        assertThat(expected)
            .as("Verify SevProceso relationships")
            .satisfies(e -> assertThat(e.getUnidadNegocio()).as("check unidadNegocio").isEqualTo(actual.getUnidadNegocio()));
    }
}
