package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SevUnidadNegocioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSevUnidadNegocioAllPropertiesEquals(SevUnidadNegocio expected, SevUnidadNegocio actual) {
        assertSevUnidadNegocioAutoGeneratedPropertiesEquals(expected, actual);
        assertSevUnidadNegocioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSevUnidadNegocioAllUpdatablePropertiesEquals(SevUnidadNegocio expected, SevUnidadNegocio actual) {
        assertSevUnidadNegocioUpdatableFieldsEquals(expected, actual);
        assertSevUnidadNegocioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSevUnidadNegocioAutoGeneratedPropertiesEquals(SevUnidadNegocio expected, SevUnidadNegocio actual) {
        assertThat(expected)
            .as("Verify SevUnidadNegocio auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSevUnidadNegocioUpdatableFieldsEquals(SevUnidadNegocio expected, SevUnidadNegocio actual) {
        assertThat(expected)
            .as("Verify SevUnidadNegocio relevant properties")
            .satisfies(e -> assertThat(e.getIdUnidadNegocio()).as("check idUnidadNegocio").isEqualTo(actual.getIdUnidadNegocio()))
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getFkIdResponsable()).as("check fkIdResponsable").isEqualTo(actual.getFkIdResponsable()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSevUnidadNegocioUpdatableRelationshipsEquals(SevUnidadNegocio expected, SevUnidadNegocio actual) {}
}
